title: my first article
author: Nick G
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  new stuff every so often
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
